### ISSUE TITLE
got segmentation fault when try to run example recursive fibonacci

### ISSUE THREAD

**Issue by digitalysin** [Microsoft/napajs#106]
<img width="680" alt="report" src="https://user-images.githubusercontent.com/399720/32212526-bbcdd0e6-be49-11e7-84b2-9d5171fe8217.png">

**Comment by helloshuangzi** [comment]
thanks for your feedback, @digitalysin . This is a known issue, and we are working on it as our top priority. Let's track it with https://github.com/Microsoft/napajs/issues/96
