### ISSUE TITLE
[UBUNTU] libstdc++.so.6: version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by darkterra** [Microsoft/napajs#107]
I, this is my  dev env :

Node Version: 7.10.0
Npm Version: 4.2.0
OS: UBUNTU

A simple require of napajs generates this error :
`Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'CXXABI_1.3.9' not found`

Is it possible to "force" napa.js to use the version of the os?
With a variable environment?

Or another solution?

Thank you in advance

**Comment by helloshuangzi** [comment]
@darkterra thx for your feedback. Please try the solution in https://github.com/Microsoft/napajs/issues/93. 
It's a bit different by the error info, but please have a try and let us know whether it works?

**Comment by darkterra** [comment]
Thank you so much @helloshuangzi  !
