### ISSUE TITLE
Stuck in function

### ISSUE THREAD

**Issue by amunhoz** [Microsoft/napajs#178]
Dont know exactly why, but i'm using in a bigger module with classes and libraries...
I've made a class (ES5 style) to use napa, but when i try to use, it get stucked (freeze and dont keep going).

Here is the class:
```
var napa = require('napajs');
var zone = napa.zone.create('packetWorker', { workers: 4 });
zone.broadcast(" \
                const fs = require('fs');\
                var xxtea = require('xxtea-node'); \
                const pako = require('pako'); \
                ")

zone.broadcast(deflateFunc.toString());
zone.broadcast(inflateFunc.toString());

function myLib(workers) {
};

myLib.deflate = async function (data, key, compress)  {
    //STUCK HERE **************************************
    var result = await zone.execute('','deflateFunc', [data, key, compress])  
    // **************************************************
    return result.value;
};

myLib.inflate = async function (data, key, compressed, type)  {
     //STUCK HERE **************************************
    var result = await zone.execute('','inflateFunc', [data, key, compressed, type])
    // **************************************************
    return result.value;
};

function deflateFunc(data, key, compress) {

    if (compress)  data = pako.deflate(data);    
    if (key !="") data = xxtea.encrypt(data, xxtea.toBytes(key));

    return data;
  }
  
function inflateFunc (data, key, compressed, type) {

    var result = false
    if (key !="")           data = xxtea.decrypt(data, xxtea.toBytes(key));
    if (compressed)         data = pako.inflate(data);
    if (type =="o" )        data = JSON.parse( xxtea.toString(data) );
    else if (type =="t" )   data = data.toString();
    if (data == null) return false;
    return data;
}

module.exports = myLib;
```
In 'deflateFunc', if i leave only the encryption line, it works. But the same module does not work on 'inflateFunc '.

However, it works fine when i use it from a simple .JS file, like this:
(Example code working... the not working code is too big to put here)
```
const packetWork = require('../lib/packetWork.js'); //FILE ABOVE
const xxtea = require('xxtea-node'); 
class testNapa {
  constructor () {

  }
  async test () {
    var data = xxtea.toBytes(JSON.stringify({A:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}))
    var result = await packetWork.deflate(data,'llalalal', true)
    var result2 = await packetWork.inflate(result,'llalalal', true, 'o')
    
    console.log(result2);
  }
}
//start test
start()
async function start () {
  var data = new testNapa();
  await  data.test();
  console.log("foi")
}

```

So, i could not find where the problem is since there is not any error message.
Another thing, it does not work if you try to create the zone instance inside a class method. It only works outside functions or classes.

**Comment by amunhoz** [comment]
By the way, i'm using:
Windows 10 x64
node 9.3.0 x64
napajs : 0.1.8

**Comment by fs-eire** [comment]
@amunhoz Could you please share the code that causes the stuck? I've taken a look into the code above and looks everything good to me so far...

For the zone creation, you should always keep a reference of the return value of `zone.create()`. If you store it into a local variable, it may be destructed when the next GC happens.

```js
// this is OK. Store the return value to somewhere.
function createMyZone() {
    return napa.zone.create('my1');
}

// don't do this
function createMyZone() {
    napa.zone.create('my1');
}
```

**Comment by amunhoz** [comment]
Here is the full code:
https://github.com/amunhoz/antz

Comments:
• It calls napa 'execute' on /antz/lib/packetWork.js:26 and  /antz/lib/packetWork.js:31 and stop there without a resolution for the promisse.
• You can check a working code with the same lib packetWork.js in /antz/tests/napa3.js.
• Dont know why, but inside a more complex application it does not work properly.

**Comment by fs-eire** [comment]
@amunhoz The stuck is caused by the fact that Node's [`Buffer`](https://nodejs.org/api/buffer.html) is not defined in Napa.js.

From Napa.js >=0.1.8 with Node.js >=9.0, javascript built-in types such as `ArrayBuffer`, `TypedArray`, `SharedArrayBuffer` and `DataView` become transportable across zones. However, `Buffer` is not in the list. Transporting a `Buffer` instance will be treated as transporting a plain object, which may cause unexpected behavior.

`Buffer` is a type defined by Node.js and it is only available in Node's context. Which means, is it not available in Napa.js's zone.

The solution is: always transport the javascript built-in buffer objects instead of Node's `Buffer` in `zone.execute()`.

In your case, the code can be updated like this:
```js
myLib.prototype.deflate = async function (data, key, compress)  {
    var buffer = new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
    var result = await this.zone.execute('','deflateFunc', [buffer, key, compress])
    return result.value;
};

myLib.prototype.inflate = async function (data, key, compressed, type)  {
    var buffer = new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
    var result = await this.zone.execute('','inflateFunc', [buffer, key, compressed, type])
    return result.value;
};
```

**Comment by amunhoz** [comment]
Yes! That was the problem.
Thanks!!!
