### ISSUE TITLE
[Proposal] update function group `zone.broadcast`

### ISSUE THREAD

**Issue by fs-eire** [Microsoft/napajs#186]
This issue will be used to track the discuss, the work and feedback for the new `zone.broadcast` function(s).

## Why need a update on `broadcast()`
There are pain points when using the current `broadcast` function:
 - **Information on `broadcast` failure is not sufficient.** (#157)
 - **No mechanism in `broadcast` to wait async function to complete.** (#158)
 - **No mechanism to transport value/objects in `broadcast`.**
    ```js
    var napa = require('napajs');
    var z1 = napa.zone.create('z1');
    var l1 = napa.sync.createLock();
    z1.broadcast(function(l){console.log(l.guardSync);}, [l1]);
    // actual console output:  undefined
    // expected console output:  [Function: guardSync]
    ```

### Native Implementation Update ###
Use `CallTask` instead of `EvalTask` in `Zone.Broadcast`'s native implementation. This enables:
 - passing error message
 - transport object
 - passing return value (useful when it is a `Promise` object)

### Existing `broadcast` function interface update ###
[see current interface detail](https://github.com/fs-eire/napajs/blob/master/docs/api/zone.md#broadcast-code)
 - `zone.broadcast(code: string): Promise<void>`
    - When the promise reject (broadcast error occurred), error message should be contained.
       (current: only error code is included)
       ```js
       z1 = napa.zone.create('z1');
       z1.broadcast("abc();").catch(function (err) {
           console.log(err);
       });
       // actual console output:  broadcast failed with result code: 5
       // expected console output:  ReferenceError: abc is not defined
       ```

 - `zone.broadcast(function: (...args: any[]) => void, args?: any[]): Promise<void>`
    - Enable object transporting
       (current: There is no `TransportContext` and trasporting behavior. All arguments are passed by `JSON.stringify()` simply)

### Enable asynchronization operation for `broadcast` ###
 - `zone.broadcast(function: (...args: any[]) => Promise<void>, args?: any[]): Promise<void>`
    - If function in any worker returns a `Promise` object, extend the `broadcast`'s returned `Promise` to resolve when promises from all workers are resolve.
       ```js
       z1 = napa.zone.create('z1');
       z2 = napa.zone.create('z2');

       z1.broadcast(function () {
         var napa = require('napajs');
         return napa.zone.get('z2').execute(function () {
           var d = new Date(); while (new Date() - d < 1000); // loop for 1 second
           console.log('napa->node');
         });
       }).then(function () {
         console.log('broadcast complete');
       });
       // actual console output:  'broadcast complete' output before 'napa->node'
       // expected console output:  'broadcast complete' output after 'napa->node'
       ```

### Add `broadcastSync` function interface update ###
Add synchronized function. The following `broadcastSync` functions will run synchronously:
 - `zone.broadcastSync(code: string): void`
 - `zone.broadcastSync(function: (...args: any[]) => void, args?: any[]): void`
 - `zone.broadcastSync(function: (...args: any[]) => Promise<void>, args?: any[]): void`

In generally, the `broadcastSync` functions do the same work as `broadcast` do, except the following differences:
 - Sync version functions return `void` instead of `Promise<void>`.
 - Sync version functions throw exception if the operation failed, instead of reject the returned Promise object.
 - Exception should be thrown if a `broadcastSync` function is called in the caller's zone. (prevent deadlock)
    ```js
    var z1_out = napa.zone.create('z1');
    z1_out.execute(function() {
        var z1_in = global.napa.zone.get('z1');
        z1_in.broadcastSync(''); // will throw.
    });
    ```

Following is a commit of the corresponding interface change (zone.ts):
https://github.com/fs-eire/napajs/commit/5e1a99c732f2baadc983f79d02c18f911ca9d60a

@helloshuangzi @daiyip

**Comment by helloshuangzi** [comment]
To clarify the behavior of `zone.broadcastSync(function: (...args: any[]) => Promise<void>, args?: any[]): void`, per discussion, it will wait the resolution of promises from all workers.

If we choose to use callTask and TransportContext for 'zone.broadcast`, and support transport in parameters, I would like it also support transport results out. Then, the interface would be like `broadcast(func: (...args: any[]) =>any, args?: any[]) : Promise<ResultList>;`
`zone.broadcastSync(function: (...args: any[]) => any, args?: any[]): ResultList`

It is just similar to 'execute(func: (...args: any[]) => any, args?: any[], options?: CallOptions) : Promise<Result>;'. The difference is broadcast will have an extra step to aggregate its results from all workers.

We can discuss its necessity / dev-cost / execution (whether leave this requirement later).

**Comment by gustavomassa** [comment]
This is an example of the issue:

```
(node:19412) UnhandledPromiseRejectionWarning: broadcast failed with result code: 5
(node:19412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,
or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19412) UnhandledPromiseRejectionWarning: broadcast failed with result code: 5
(node:19412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,
or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19412) UnhandledPromiseRejectionWarning: broadcast failed with result code: 5
(node:19412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,
or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```
