### ISSUE TITLE
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found on RED-Hat(RHEL-6.5) Linux 

### ISSUE THREAD

**Issue by MAYANKATUL** [Microsoft/napajs#192]
Hello,

I’m using node module napajs on RED-Hat(RHEL-6.5) Linux machine. On Linux machine, node version is 6.10.0 and gcc version is 4.4.7.
I wrote a simple node program using napajs module.
![pic1](https://user-images.githubusercontent.com/14525326/35975036-5a40e3fc-0d01-11e8-8ed9-bc4f66954646.png)
When I execute this program, first I faced GLIBC-2.14 library issue.
![pic2](https://user-images.githubusercontent.com/14525326/35975054-6c7cd44a-0d01-11e8-8aae-3bf3fda369f1.png)
For solving this issue, I extracted the tar of GLIBC-2.14 and provided the path of GLIBC-2.14 library in LD_LIBRARY_PATH using following steps-

1.	tar xvfz glibc-2.14.tar.gz
2.	cd glibc-2.14
3.	mkdir build
4.	cd build
5.	../configure --prefix=/opt/glibc-2.14
6.	make
7.	sudo make install
8.	export LD_LIBRARY_PATH=/opt/glibc-2.14/lib:$LD_LIBRARY_PATH
Then again execute the code and now I’m facing Segmentation fault (core dumped) issue.
![pic3](https://user-images.githubusercontent.com/14525326/35975095-898e7c32-0d01-11e8-86a2-c692cd99a6cf.png)
And now, I’m stuck at this stage. I would appreciate if you provide the better approach to fix this issue.

Thanks in advance.

**Comment by helloshuangzi** [comment]
Your testing code works well on my client Ubuntu 16.0. 
About it on your Redhat client:
    Did you use the pre-built napa? `npm install napajs` will install pre-built napajs if available for your client environment. You can see `info NAPA_INSTALL downloading the pre-build binaries ...` if you installed the pre-built version. 
    If you used the pre-built version, I doubt there is some inconsistency. You may try to build napa in your client by following [Build Napa.js](https://github.com/Microsoft/napajs/wiki/build-napa.js).

**Comment by MAYANKATUL** [comment]
@helloshuangzi I did the same thing that was defined on link [Build Napa js](https://github.com/Microsoft/napajs/wiki/build-napa.jsl). After that I faced that issue.

**Comment by helloshuangzi** [comment]
Thanks for your feedback, @MAYANKATUL !
Could you try with newer gcc versions? I don't have a redhat environment, but I encountered 'seg fault' on Ubuntu 14 with gcc 4.8, while gcc 5.+ and 6.+ fixed it.

**Comment by dmitrif** [comment]
I am seeing the same thing on Debian Kernel v4.4.115, with prebuilt napaJs:

```fes_1  | Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /var/frontend/node_modules/napajs/bin/napa-binding.node)
fes_1  |     at Error (native)
fes_1  |     at Object.Module._extensions..node (module.js:597:18)
fes_1  |     at Module.load (module.js:487:32)
fes_1  |     at tryModuleLoad (module.js:446:12)
fes_1  |     at Function.Module._load (module.js:438:3)
fes_1  |     at Module.require (module.js:497:17)
fes_1  |     at require (internal/module.js:20:19)
fes_1  |     at Object.<anonymous> (/var/frontend/node_modules/napajs/lib/binding.js:22:22)
fes_1  |     at Module._compile (module.js:570:32)
fes_1  |     at Object.Module._extensions..js (module.js:579:10)```

**Comment by dmitrif** [comment]
According to another issue log, installing `glibc` inside the container, should work. Thank you.
