### ISSUE TITLE
Often Crash when using node 8.10.0 on ubuntu 16.04

### ISSUE THREAD

**Issue by zhanghuanrong** [Microsoft/napajs#200]

**Comment by fs-eire** [comment]
It looks that Napa crashes on the latest Node.js version in Linux platform.

I am investigating the issue.

**Comment by fs-eire** [comment]
UPDATE: it looks the crash is not affecting Node 9.x. Crash can be reproduced on Node 6.x and 8.x

**Comment by fs-eire** [comment]
Fixed in 0.2.1
