### ISSUE TITLE
[Question] Is there any Example for working concurrent file read and write in napajs ?

### ISSUE THREAD

**Issue by saeedtabrizi** [Microsoft/napajs#218]
Hi 
I need an example for IO bound related example in napajs :
-  example for handling concurrent file read and write 
-  example for handling network send and receive data . 
Is there any example or guide here ? 
Thanks

**Comment by fs-eire** [comment]
Hello @saeedtabrizi , in general it is not encouraged to use Napajs to process I/O bound tasks. Node has done a lot of effort to improve performance by using async I/O tasks. Using the non-blocking async version of filesystem and networking APIs is usually the best option.

Napa.js helps when you have heavy CPU bounded tasks.

**Comment by saeedtabrizi** [comment]
Hi @fs-eire
Good notes :+1: 
Thanks
