### ISSUE TITLE
broadcast err

### ISSUE THREAD

**Issue by yihchu** [Microsoft/napajs#226]
let code = 'var j = require(\\\'./test-job\\\');';
zone.broadcast(code).then(() => {console.log('>>>>> broad cast code success')}).catch((err) => {console.log('>>>>> broad cast code failed');console.log(err)})

err: SyntaxError: Unexpected string

**Comment by fs-eire** [comment]
looks like syntax error in your javascript code...

**Comment by yihchu** [comment]
3Q, I made a mistake ...
