### ISSUE TITLE
Error: %1 is not a valid Win32 application. on azure nodejs 

### ISSUE THREAD

**Issue by jdadojr** [Microsoft/napajs#237]
Running on node 8.4.0 

2018-05-16T18:44:07  Welcome, you are now connected to log-streaming service.
Wed May 16 2018 18:44:24 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
Error: %1 is not a valid Win32 application.

\\?\D:\home\site\wwwroot\node_modules\napajs\bin\napa-binding.node
    at Object.Module._extensions..node (module.js:602:18)

**Comment by fs-eire** [comment]
Is there more information about the error? I cannot figure out the problem with those logs.

BTW, could you try command `node -e "console.log(require('napajs'))"` in folder D:\home\site\wwwroot and check the output?

**Comment by fs-eire** [comment]
let's try to figure out more:
- are you using a 32 bit node.exe?
- is there a filesystem permission issue? (D:\home\site\wwwroot looks like an IIS folder)

**Comment by jdadojr** [comment]
Hi,
  No, I am using 64-bit
  This is just a plain App Services running Node and I think via IIS

General settings
.NET Framework version   v4.7
PHP version   Off
App Service supports installing newer versions of Python. Click here to learn more.
Python version   Off
Java version   Off
Java minor version   
Java web container   
Platform   64-bit
Web sockets   Off 
Always On   
Managed Pipeline Version Integrated Classic
HTTP Version 1.1 
ARR Affinity Off 
Auto Swap Off
Auto Swap Slot 
FTP access  Disable
Remote debugging Off 
Remote Visual Studio version 2012 2013 2015 2017

**Comment by fs-eire** [comment]
We do not offer pre-built binaries for x86 environment.

If you are using x64 node, when you command `npm install napajs`, the file napa.dll and napa-binding.node will be downloaded automatically from github.com by the install script.

If you are using x86 node, the install script will try to find the pre-build binaries (which will fail), and fall back to kick a build. If the machine you are using is not ready for [building napajs](https://github.com/Microsoft/napajs/wiki/build-napa.js), the build will fail and the binaries will be missing so you will have no runtime binaries to use.

If you use a x64 node to run the `npm install napajs` and get those binaries for x64, and deploy the folder to a x86 environment, node will simply fail to load the addon.

Let's get back to your case:

D:\home\site\wwwroot>node -p "process.arch"
ia32

So you are using the 32 bit node.exe. My guess is you have the x64 napa-binding.node under folder D:\home\site\wwwroot\node_modules\napajs\bin\.

**Comment by jdadojr** [comment]
Hi,

 Thanks , your comment helped. By using iisnode.yml to point the node to my amd64 node.exe, I 
 managed to get it to work.
:)
