### ISSUE TITLE
Beginners Question: costs of napa.js

### ISSUE THREAD

**Issue by BenDietze** [Microsoft/napajs#257]
Hi! This is an evolutionary JavaScript Project, and i found no chatroom to talk about - i hope, this issue here is ok :)

I have at least two questions:

How affects napa.js node workers (or threads) and vice versa? The docs of napa.js are showing perfect scaled CPU-time to the number of available threads - or physical cores? Whats about running on a 4-core machine (or like 2 cores with 4 Hyperthreads) napa.js and node cluster with 4 workers? Is there a gap using both? I would like to think minimal, if the workers are morely bound to IO and the Isolates due napa.js for CPU-bound jobs? Is there something to say about that we are now running 4 + 4 threads?

And, on the other side - what are the costs of running napa.js? If i run a simple node-job on one side and on the other the same with napa.js - is there a rule / measurement about the costs of starting _simplest_ napa.js calculations? What i am meaning here is morely: could it makes sense to test everything against napa.js or will it help morely only in very heavy calculations?

I know we can talk here only about vague rules - but that would help me.

I would be very thankful to for all experiences of others while developing for webservices and so on :)

Thank you

**Comment by fs-eire** [comment]
When talking about performance, it's always depending on a lot of things, the spec of the machine (CPU cores, memory and so on), the services and applications running on the machines, and how the code is written.

To understand how napa.js helps the performance improvement, it is important to understand the Node.js's [event loop](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/) model. async IO is introduced to help to get rid of blocking IO, but all javascript code are running in the main thread. this may not be an issue for a typical Node.js application, which usually does not have a heavy process per request.

If you have the requirement of heavy process pre request, say, you need to do something using javascript which spend 0.1 seconds per request, this means you won't be able to handle more than 10 request per seconds. This is when napa.js or node clusters come to the scope.

to answer your question:
 1- it depends on what your application do and how it is implemented. Napa.js helps when you javascript code spend a lot of time. please do profiling and check the result

2- the cost of napa.js contains the time cost and memory cost.
it does spend some time when the first time napa.js is loaded (`require('napajs');`) and has overhead for each call on zones. those number can be found in benchmark.
memory cost mainly depends on the module that you loaded into each worker. check the runtime memory consume statistics.
the recommended way of using napa.js is to delegate heavy tasks to zones, especially when those tasks are time-consuming CPU bounded javascript code.

**Comment by BenDietze** [comment]
Thank you very much - i haven't recognized any data on overheads in the benchmark - maybe, my english is buggy. I will have a next look.

Would be nice if the issue can stay open a little time if others would like to talk about some experience.

Lastly, i got now to another question. Say, there is a node cluster with 4 workers and because of random requests, all workers using napa unsorted - is there something problematic?

**Comment by BenDietze** [comment]
Oh, ok, that will clearify most for me.

Thank you :+1:
