### ISSUE TITLE
Add 'description' field in package.json

### ISSUE THREAD

**Issue by daiyip** [Microsoft/napajs#60]
## Issue:

Now `npm search` will show snippet from README.md, which is 
```
[![Build Status for Linux/MacOS](https://travis-ci.org/Microsoft/napajs.svg?branch=master)](https://travis-ci.org/Microsoft/napajs) [![Build Status for Windows](https://ci.appveyor.com/api/projects/status/github/Microsoft/napajs?branch=master&svg=true)](
```

Adding "description" field in package.json will solve this.

**Comment by fs-eire** [comment]
Thanks for reporting. Created PR #61 for a fix.

**Comment by fs-eire** [comment]
Resolved in commit https://github.com/Microsoft/napajs/commit/a63d43bf4abf39f1e1d1be72d4b8489e947c7a7c.
