### ISSUE TITLE
zone term conflict with zone.js

### ISSUE THREAD

**Issue by gdi2290** [Microsoft/napajs#74]
[zone.js by Angular](https://github.com/angular/zone.js)
[Zones spec proposal for TC39](https://github.com/domenic/zones)
[Zones from Dart lang](https://www.dartlang.org/articles/libraries/zones)

It might be a good idea to mention that the term zone used here is different from what JavaScript developers might have heard of in the past (from Angular which created zone.js)

**Comment by daiyip** [comment]
Addressed by PR #85, thanks for the suggestion.
