### ISSUE TITLE
[UNIX] Prebuilt binaries are not working.

### ISSUE THREAD

**Issue by fs-eire** [Microsoft/napajs#80]
## Problem
  Pre-built binaries are not working on Linux and MacOS.
```
npm install napajs
node -e "require('napajs')"
```
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: libnapa.so: cannot open shared object file: No such file or directory

## Solution
  Update napa.js to version 0.1.4 or later to resolve this issue.

## ~~Workaround~~
 ~~1.  `export LD_LIBRARY_PATH=./node_modules/napajs/bin:$LD_LIBRARY_PATH
` before launch node.~~
 ~~2.  Use `npm install --no-fetch` so the install script will fallback to build napajs. See [this](https://github.com/Microsoft/napajs/wiki/build-napa.js) for more information.~~

## Root Cause
  The file 'napa-binding.node' was using absolute path in its rpath before v0.1.4. This causes the pre-built file cannot be loaded in runtime.

**Comment by snood1205** [comment]
This suggestion might sound a bit odd, but what about the `npm` package for `napajs` relying on having `libnapa` instead of installing native extensions like it does right now and break out `libnapa` into its own shared lib.

**Comment by daiyip** [comment]
Thanks for the suggestion. Do you mean to publish a NPM module 'libnapa', and have 'napajs' depend on it?

**Comment by snood1205** [comment]
Yeah pretty much for `libnapa` to be distributed as a `.node` addon binary on its on and then have `napajs` depend on it. It seems like breaking up the JS and C/C++ into different repos would allow for a bigger focus on portability within the `libnapa` repo as people who want to work on the C/C++ part of this would be drawn to `libnapa`.

**Comment by daiyip** [comment]
At a glance, `napajs` is just a node binding of `libnapa`, an one-way dependency. But the concept of [Node zone](https://github.com/Microsoft/napajs/blob/master/docs/api/zone.md#node-zone) makes things interesting. As Node event loop is exposed via `Zone` interface, workers in Napa zone can offload IO tasks to Node when Napa doesn't support IO related Node modules. Under this design, `libnapa` also collaborate with `napajs` to access Node event loop. So separation of them is not feasible here.

**Comment by daiyip** [comment]
Close as solved.

**Comment by woodyrew** [comment]
I still get an error with `0.1.4`:
```bash
$ npm ls napajs
napa-test@0.1.0 /home/username/napa-test
└── napajs@0.1.4
```

```bash
$ node -e "require('napajs')"
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/username/napa-test/node_modules/napajs/bin/libnapa.so)
...
```

Even with the paths added.
```
export LD_LIBRARY_PATH=./node_modules/napajs/bin:$LD_LIBRARY_PATH
```

**Comment by helloshuangzi** [comment]
@woodyrew thx for your feedback. Please refer to [issue#93](https://github.com/Microsoft/napajs/issues/93) for 'GLIBCXX_3.4.22' error.
