### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by igeligel** [Microsoft/napajs#90]
Under which license this project is released? Since most of the [Microsoft](https://github.com/Microsoft) open source work is released under [MIT](https://opensource.org/licenses/MIT) i recommend this license. Great project btw. like a lot of the Microsoft projects 👍

**Comment by helloshuangzi** [comment]
@igeligel napa.js is under MIT license.

**Comment by daiyip** [comment]
Added to README in PR #91.
