### ISSUE TITLE
Introduce Buffer class that can be transferred across workers without copying

### ISSUE THREAD

**Issue by daiyip** [Microsoft/napajs#92]
The problem is raised from [sorting big array in parallel](https://stackoverflow.com/questions/46864497/node-js-parallel-tasks-with-napajs)

This is a common pattern to share big payload across workers. We also had it tracked in the [roadmap](https://github.com/Microsoft/napajs/wiki/roadmap).

**Comment by daiyip** [comment]
Thanks for checking in. Actually we are in an early discussion on this feature. 
Before we have a conclusion, I am sharing some of initial thoughts here. @barrotsteindev we can also loop you in the discussion if you have any feedback.

We tend to introduce namespace `napa.shared` to umbrella all objects that can be shared across workers.

Initially, there will be an `napa.shared.ArrayBuffer`, which is a [shareable wrap]() that can pass across workers, holding a `std::shared_ptr<void>`, which can be used as external buffer to construct  [v8::ArrayBuffer](http://bespin.cz/~ondras/html/classv8_1_1ArrayBuffer.html) with small cost. [AllocatorWrap](https://github.com/Microsoft/napajs/blob/master/src/module/core-modules/napa/allocator-wrap.h) is an example of this pattern. We need to study how this class can interact with Node buffer with minimum cost.

Naturally, we may introduce  `napa.shared.ArrayBufferView` as a cross-isoalte mapping to [v8::ArrayBufferView](http://bespin.cz/~ondras/html/classv8_1_1ArrayBufferView.html), so that  other typed arrays like `napa.shared.Uint32Array` can be easily obtained from it.

For best usability of API, we may need some iteration to finalize. But your comment is highly welcome.

**Comment by daiyip** [comment]
Btw, the [SharedArrayBuffer](http://2ality.com/2017/01/shared-array-buffer.html) proposal in ES2017 is what exactly we want to achieve here. This proposal addresses web workers in the browser, and our solution seems a reasonable parallel in Node system.

**Comment by barrotsteindev** [comment]
Id love to take part of the discussion, and perhaps the development if time decides to be on my side.
Sticking to es2017 does sound like a good plan.

**Comment by daiyip** [comment]
Since this is our first time working together with community to design a feature. We tried to sort out an effective process. Here is the proposal:

1) First pull request will start from docs folder, adding a one page to `docs/design` or `docs/api`. Once the spec is signed off by all required member, we get the work items and divide.
2) PR for individual items.

I have asked the team to loop you in this feature. Thanks.

**Comment by barrotsteindev** [comment]
Thanks a lot.
I appreciate the effort

**Comment by helloshuangzi** [comment]
Hi, @barrotsteindev and @daiyip, I did some investigation about this feature. 
Both V8 and Node >= v9.0.0 have supported experimental [SharedArrayBuffer of ECMA2017](https://tc39.github.io/ecma262/2017/#sec-sharedarraybuffer-objects). The major concepts involved are SharedArrayBuffer, TypedArray and Atomics. Please refer to [d8-worker-sharedarraybuffer](https://github.com/v8/v8/blob/f2bd913cd459854894447f5422a953d23fa4e7ba/test/mjsunit/d8-worker-sharedarraybuffer.js) and [worker-memory](https://github.com/v8/v8/blob/52d8c2a42241b979add379f2a1ea4f7113f9a5c1/test/mjsunit/wasm/worker-memory.js).
So we may don't need to define napa buffer from scratch. A [transportable](https://github.com/Microsoft/napajs/blob/master/lib/transport/transportable.ts) verison of SharedArrayBuffer will serve our purpose.
Welcome your comments!

**Comment by helloshuangzi** [comment]
Hi, @barrotsteindev, Based on the above investigation, I just made [the design]( https://github.com/helloshuangzi/napajs-1/blob/e98de45bf67d814b906c99eebd672a006e0028d7/docs/design/transport-js-builtins.md ) and its 1st [implemention](https://github.com/Microsoft/napajs/pull/151). 
Welcome your comments!

**Comment by helloshuangzi** [comment]
The 1st implementation was merged with #151.
Some open issues about it were created and tracked separately. #149 #150 , and will add examples update doc/api/transport later.
