### ISSUE TITLE
recursive-fibonacci demo errors 

### ISSUE THREAD

**Issue by welefen** [Microsoft/napajs#95]
I try to run code in https://github.com/Microsoft/napajs/blob/master/examples/tutorial/recursive-fibonacci/recursive-fibonacci.js. When is change to run `run(20)`, it has errors in below:

```
node(10345,0x7fffb809e3c0) malloc: *** error for object 0x103417b50: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    10345 abort      node napa.js
```

**Comment by vaibhav93** [comment]
I get this error. Not creating a separate issue since it might be related.
node recursive-fibonacci.js 

        Nth     Fibonacci       # of workers    latency in MS
        -----------------------------------------------------------
        10      55              4               22
        11      89              4               20
        12      144             4               30
        13      233             4               40
        14      377             4               86
*** Error in `node': free(): corrupted unsorted chunks: 0x00007f7a6c0d7410 ***
Segmentation fault (core dumped)
`

**Comment by vaibhav93** [comment]
Estimate pi example failing too
node estimate-pi-in-parallel.js 

        # of points     # of batches    # of workers    latency in MS   estimated π     deviation
        ---------------------------------------------------------------------------------------
        4000000         1               4               107             3.140193        0.001399654
        4000000         2               4               82              3.141261        0.0003316536
*** Error in `node': double free or corruption (out): 0x00007fb9a8072020 ***
Aborted (core dumped)

**Comment by helloshuangzi** [comment]
@welefen @vaibhav93 We just verified it works well by node <= v8.4.0 on linux, and it will fail with random callstacks by node >=v8.5.0
this issue is duplicated with https://github.com/Microsoft/napajs/issues/96. I am closing it, and let's track it by https://github.com/Microsoft/napajs/issues/96
